services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-api}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-postgres}"]
      interval: 5s
      retries: 5
      timeout: 10s
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
