services:
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
      POSTGRES_DB: ${SQL_DB:-api}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${SQL_USER:-postgres}"]
      interval: 5s
      retries: 5
      timeout: 10s
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}

  migrator:
    image: brownhounds/migoro:0.1.0
    env_file:
      - ./.env
    environment:
      - SQL_HOST=postgres
    volumes:
      - ./migrations:/migrations
    command: migrate
    depends_on:
      postgres:
        condition: service_healthy

  api:
    build:
      context: .
    env_file:
      - ./.env
    environment:
      - SQL_HOST=postgres
    depends_on:
      migrator:
        condition: service_completed_successfully
    ports:
      - 8080:8080
