CREATE TABLE dogs (
    id UUID PRIMARY KEY NOT NULL DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER updated_at_users BEFORE UPDATE ON dogs FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();

INSERT INTO dogs (name) VALUES ('Cookie'), ('Franek');
